### ISSUE TITLE
`yarn start`시 `API_URL`/`SENTRY_DSN` 환경 변수가 필요하나 문서화되어있지 않음

### ISSUE THREAD

**Issue by saschanaz** [chinchiilla/corona-live-v4#5]
https://github.com/chinchiilla/corona-live-v4/blob/42cf4b0508f02693f36a94c1aef9927a59bd3cd3/vite.config.ts#L10

환경 변수 없이 실행할 경우 아래와 같은 오류가 발생합니다.

```
error when starting dev server:
Error: vite-plugin-environment: the `API_URL` environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://github.com/ElMassimo/vite-plugin-environment for guidance.
    at throwMissingKeyError (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite-plugin-environment\dist\index.cjs:45:9)
    at C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite-plugin-environment\dist\index.cjs:34:7
    at Array.reduce (<anonymous>)
    at defineEnvVars (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite-plugin-environment\dist\index.cjs:31:15)
    at Object.config (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite-plugin-environment\dist\index.cjs:58:24)
    at resolveConfig (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite\dist\node\chunks\dep-f5552faa.js:74691:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite\dist\node\chunks\dep-f5552faa.js:60326:20)
    at async CAC.<anonymous> (C:\Users\Kagami\Documents\GitHub\corona-live-v4\node_modules\vite\dist\node\cli.js:688:24)
```

**Comment by elliott44k** [comment]
본인 api_url 받아야되지 않아요?

**Comment by saschanaz** [comment]
받는 방법이 있나요?

**Comment by chinchiilla** [comment]
[9dd6a4a](https://github.com/chinchiilla/corona-live-v4/commit/9dd6a4ac19f9b15a28ff6430b9c70d5c664450ca) 해결되었습니다
